### ISSUE TITLE
Missing specgen in stoke?

### ISSUE THREAD

**Issue by moyix** [StanfordPL/strata#1] opened 2016-08-16 16:14 UTC
The instructions given for building strata don't work out of the box, failing here:

```
moyix@lorenzo:~/git$ git clone https://github.com/StanfordPL/strata.git
Cloning into 'strata'...
remote: Counting objects: 4263, done.
remote: Total 4263 (delta 0), reused 0 (delta 0), pack-reused 4263
Receiving objects: 100% (4263/4263), 638.28 KiB | 0 bytes/s, done.
Resolving deltas: 100% (2897/2897), done.
Checking connectivity... done.
moyix@lorenzo:~/git$ cd strata
moyix@lorenzo:~/git/strata$ make
cd stoke && ./configure.sh
/bin/sh: 1: ./configure.sh: not found
Makefile:12: recipe for target 'stoke' failed
make: *** [stoke] Error 127
moyix@lorenzo:~/git/strata$ ls stoke/
```

Next I tried cloning stoke into the strata directory and building. I had to pass CC and CXX set to gcc-4.9/g++4.9 to get it to build. This builds, but then when trying `./strata run`, I get:

```
moyix@lorenzo:~/git/strata$ ./strata run
[  ] starting initialization ...
[  ] producing pseudo functions ...
[  ] Running command 'scripts/python/create_functions.py /home/moyix/git/strata/resources/function-templates /home/moyix/dev/output-strata/functions'
Processed 15 split-in-two templates, 4 move-byte templates and 6 flag templates to get a total of 316 funcions.
[  ] initialize configuration using specgen init ...
[  ] Running command 'stoke/bin/specgen init --workdir /home/moyix/dev/output-strata'
[error] (run-main-0) java.io.IOException: Cannot run program "stoke/bin/specgen" (in directory "/home/moyix/git/strata"): error=2, No such file or directory
java.io.IOException: Cannot run program "stoke/bin/specgen" (in directory "/home/moyix/git/strata"): error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
        at scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:69)
        at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.run(ProcessBuilderImpl.scala:100)
        at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.run(ProcessBuilderImpl.scala:99)
        at strata.util.IO$.run(IO.scala:52)
        at strata.util.IO$.runPrint(IO.scala:78)
        at strata.util.IO$.safeSubcommand(IO.scala:103)
        at strata.Initialize$.run(Initialize.scala:49)
        at strata.Driver.run(Driver.scala:27)
        at strata.Strata$$anonfun$7.apply(main.scala:106)
        at strata.Strata$$anonfun$7.apply(main.scala:85)
        at strata.Strata$$anonfun$main$1.apply(main.scala:346)
        at strata.Strata$$anonfun$main$1.apply(main.scala:344)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at strata.Strata$.main(main.scala:344)
        at strata.Strata.main(main.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:187)
        at java.lang.ProcessImpl.start(ProcessImpl.java:130)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
        at scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:69)
        at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.run(ProcessBuilderImpl.scala:100)
        at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.run(ProcessBuilderImpl.scala:99)
        at strata.util.IO$.run(IO.scala:52)
        at strata.util.IO$.runPrint(IO.scala:78)
        at strata.util.IO$.safeSubcommand(IO.scala:103)
        at strata.Initialize$.run(Initialize.scala:49)
        at strata.Driver.run(Driver.scala:27)
        at strata.Strata$$anonfun$7.apply(main.scala:106)
        at strata.Strata$$anonfun$7.apply(main.scala:85)
        at strata.Strata$$anonfun$main$1.apply(main.scala:346)
        at strata.Strata$$anonfun$main$1.apply(main.scala:344)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at strata.Strata$.main(main.scala:344)
        at strata.Strata.main(main.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
[trace] Stack trace suppressed: run last compile:run for the full output.
java.lang.RuntimeException: Nonzero exit code: 1
        at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error] (compile:run) Nonzero exit code: 1
[error] Total time: 2 s, completed Aug 16, 2016 12:12:12 PM
```

Any idea how I can build `specgen`? I tried digging through the stoke git history but couldn't figure out when it was added or removed.

**Comment by stefanheule** [comment] 2016-08-16 16:36
That's an oversight in the instructions.  strata uses git submodules, in particular for stoke, so you should not have to check out stoke manually, but instead just initialize the submodule.  One a fresh clone, do `git clone --recursive https://github.com/StanfordPL/strata.git` (not the recursive flag), or do `git submodule update --init --recursive` on an existing checkout.  I've updated the instructions at https://stefanheule.com/s/projects/strata/ accordingly.  Sorry for that.

As a side note: strata uses a special version of stoke (the one in the feature-strata branch), that includes the specgen tool.  You probably checked out the develop branch of stoke, which is why it didn't work.

**Comment by stefanheule** [comment] 2016-08-16 16:36
I'm closing this, but feel free to reopen if the problem is not resolved.

**Closed as completed by stefanheule** 2016-08-16 16:36 UTC
